// Card Play Conditions Enum
//
// UE4 name of this enum: CardPlayConditions_Enum

// UE4 Asset Name: CardPlayConditions_Enum
// UE4 Package Name: "/Game/CCGToolkit/Blueprints/Enums/Gameplay_Enums/CardPlayConditions_Enum"

annotations: &reflected_data &name("CardPlayConditions_Enum")

$$ @@

CardPlayConditions_Enum !@@none
CardPlayConditions_Enum !@@play_at_start_of_turn_ai_only_
CardPlayConditions_Enum !@@play_at_end_of_turn_ai_only_
CardPlayConditions_Enum !@@play_when_low_health_self_
CardPlayConditions_Enum !@@play_when_high_health_self_
CardPlayConditions_Enum !@@play_when_creatures_are_on_the_board_self_
CardPlayConditions_Enum !@@play_when_creatures_are_on_the_board_self_ai_only_
CardPlayConditions_Enum !@@play_when_creatures_are_on_the_board_opponent_
CardPlayConditions_Enum !@@play_when_creatures_are_on_the_board_opponent_ai_only_
CardPlayConditions_Enum !@@play_when_there_are_cards_in_the_graveyard
CardPlayConditions_Enum !@@play_when_there_are_cards_in_the_graveyard_ai_only_
CardPlayConditions_Enum !@@play_when_low_playable_card_in_hand_ai_only_
CardPlayConditions_Enum !@@card_play_conditions_max

$$ @@!
// CardPlayConditions_Enum
// EnumPath: /Game/CCGToolkit/Blueprints/Enums/Gameplay_Enums/CardPlayConditions_Enum.CardPlayConditions_Enum

()

  [
  @@none:                                                   CardPlayConditions_Enum!int(0)
  @@play_at_start_of_turn_ai_only_:                         CardPlayConditions_Enum!int(1)
  @@play_at_end_of_turn_ai_only_:                           CardPlayConditions_Enum!int(2)
  @@play_when_low_health_self_:                             CardPlayConditions_Enum!int(3)
  @@play_when_high_health_self_:                            CardPlayConditions_Enum!int(4)
  @@play_when_creatures_are_on_the_board_self_:             CardPlayConditions_Enum!int(5)
  @@play_when_creatures_are_on_the_board_self_ai_only_:     CardPlayConditions_Enum!int(6)
  @@play_when_creatures_are_on_the_board_opponent_:         CardPlayConditions_Enum!int(7)
  @@play_when_creatures_are_on_the_board_opponent_ai_only_: CardPlayConditions_Enum!int(8)
  @@play_when_there_are_cards_in_the_graveyard:             CardPlayConditions_Enum!int(9)
  @@play_when_there_are_cards_in_the_graveyard_ai_only_:    CardPlayConditions_Enum!int(10)
  @@play_when_low_playable_card_in_hand_ai_only_:           CardPlayConditions_Enum!int(11)
  @@card_play_conditions_max:                               CardPlayConditions_Enum!int(12)
  ]

$$ .
