// GameInstance: high-level manager object for an instance of the running game.
// Spawned at game creation and not destroyed until game instance is shut down.
// Running as a standalone game, there will be one of these.
// Running in PIE (play-in-editor) will generate one of these per PIE instance.
//
// UE4 name of this class: GameInstance

annotations: &reflected_cpp &name("GameInstance")

$$ .
