// Isis Game State BP
//
// UE4 name of this class: IsisGameState_BP_C

// UE4 Asset Name: IsisGameState_BP
// UE4 Package Name: "/Game/GameInformation/IsisGameState_BP"

annotations: &reflected_data &name("IsisGameState_BP_C")

$$ @

&raw("BP Grid Manager Ref") BP_GridManager !@bp_grid_manager_ref // BP Grid Manager Ref

$$ @initialize
// Initialize
//
// UE4 name of this method: Initialize

&aka("Initialize")

() 

$$ .
