// Isis Pawn BP
//
// UE4 name of this class: IsisPawn_BP_C

// UE4 Asset Name: IsisPawn_BP
// UE4 Package Name: "/Game/IsisPawn_BP"

annotations: &reflected_data &name("IsisPawn_BP_C")

$$ @

/* &raw("UberGraphFrame")     PointerToUberGraphFrame !@uber_graph_frame    // Currently unsupported */
&raw("PlayerCharacter_BP") ChildActorComponent !@player_character_bp // Player Character BP
&raw("Sphere")             StaticMeshComponent !@sphere              // Sphere

$$ .
